=== l3xfrant3s/Cosas-que-hago-en-VS-Code/LND/UT 6/6.5/BDcomponentes/BDcomponentes.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.l3xfrant3s.com"
elementFormDefault="qualified">
    <element name="BDcomponentes">
        <complexType>
            <sequence>
                <element name="componente" minOccurs="1" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="nombre" type="string"/>
                            <choice>
                                <element name="precio">
                                    <simpleType>
                                        <restriction base="decimal">
                                            <minExclusive value="0"/>
                                        </restriction>
                                    </simpleType>
                                </element>
                                <element name="precioigic">
                                    <simpleType>
                                        <restriction base="decimal">
                                            <minExclusive value="0"/>
                                        </restriction>
                                    </simpleType>
                                </element>
                            </choice>
                            <element name="tipo" type="string" minOccurs="1" maxOccurs="unbounded"/>
                            <element name="peso" type="positiveInteger"/>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== l3xfrant3s/Cosas-que-hago-en-VS-Code/LND/UT 6/6.5/BDcomponentes/BDcomponentes.xml
<?xml version="1.0" encoding="UTF-8"?>
<BDcomponentes
xmlns="https://www.l3xfrant3s.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.l3xfrant3s.com BDcomponentes.xsd">
    <componente>
        <nombre>Perno</nombre>
        <precio>0.05</precio>
        <tipo>Unión</tipo>
        <tipo>Acero</tipo>
        <peso>20</peso>
    </componente>
    <componente>
        <nombre>Destornillador de precisión</nombre>
        <precioigic>6.99</precioigic>
        <tipo>Torx</tipo>
        <peso>150</peso>
    </componente>
</BDcomponentes>
