=== l3xfrant3s/Cosas-que-hago-en-VS-Code/LND/UT 6/6.5/bdusuarios/bdusuarios.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.l3xfrant3s.com"
elementFormDefault="qualified">
    <element name="bdusuarios">
        <complexType>
            <sequence>
                <element name="usuario" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="nombre" type="string"/>
                            <element name="email" type="string"/>
                            <element name="fechaNac"/>
                        </sequence>
                        <attribute name="clave" type="string" use="required"/>
                        <attribute name="dni" use="required">
                            <simpleType>
                                <restriction base="string">
                                    <pattern value="[0-9]{8}[TRWAGMYFPDXBNJZSQVHLCKE]"/>
                                </restriction>
                            </simpleType>
                        </attribute>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== l3xfrant3s/Cosas-que-hago-en-VS-Code/LND/UT 6/6.5/bdusuarios/bdusuarios.xml
<?xml version="1.0" encoding="UTF-8"?>
<bdusuarios
xmlns="https://www.l3xfrant3s.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.l3xfrant3s.com bdusuarios.xsd">
    <usuario clave="123" dni="11111111H">
        <nombre>Juan</nombre>
        <email>juan@hotmail.com</email>
        <fechaNac />
    </usuario>
    <usuario clave="321" dni="11233211B">
        <nombre>Yo</nombre>
        <email>yo@elvr.es</email>
        <fechaNac />
    </usuario>
</bdusuarios>
